prSections:
- title: 👀 @me
  filters: is:open -status:failure review-requested:@me draft:false
- title: 👷🏽 @pb
  filters: is:open author:HoneyryderChuck author:@me author:4ndypanda
- title: ✴︎ @pb
  filters: author:HoneyryderChuck author:@me author:4ndypanda
- title: 🔨 @me
  filters: is:open author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 30
  issuesLimit: 30
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 25
        grow: true
      title:
        grow: true
      author:
        width: 15
        grow: true
      assignees:
        hidden: true
        width: 20
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 5
keybindings:
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: delta
confirmQuit: false
smartFilteringAtLaunch: false
showAuthorIcons: false
